#!/bin/bash
# 基本软件安装
sudo apt-get install -y git git-review git-svn firefox firefox-locale-zh-hans sublime-text
#安装 mysql 数据库 修改端口3306为3309
sudo apt-get install -y install mysql-client mysql-server
sed -i -e"s/^bind-address\s*=\s*127.0.0.1/bind-address = 0.0.0.0/" /etc/mysql/my.cnf
sed -i -e"s/^port\s*=\s*3309/port = 3309/" /etc/mysql/my.cnf
# vim
# 获取配置
curl https://j.mp/spf13-vim3 -L > spf13-vim.sh && sh spf13-vim.sh
# curl https://j.mp/spf13-vim3 -L -o - | sh #更新
# casper
git clone git://github.com/n1k0/casperjs.git
cd casperjs
ln -sf `pwd`/bin/casperjs /usr/local/bin/casperjs
#nodejs 和 npm 安装
curl -sL https://deb.nodesource.com/setup | sudo bash -
sudo apt-get install -y nodejs
#风格检查
sudo npm install -g jscs
sudo npm install -g jshint
sudo npm install -g coffeelint
#coffeelint -f ~/coffeelint.json <coffee-file>
sudo npm install -g csslint
#csslint --ignore=adjoining-classes,text-indent,import,ids --format=compact <css-file>

# 安装 docker
sudo apt-get update
sudo apt-get install docker.io
sudo ln -sf /usr/bin/docker.io /usr/local/bin/docker
sudo sed -i '$acomplete -F _docker docker' /etc/bash_completion.d/docker.io
# 或者
# curl -s https://get.docker.io/ubuntu/ | sudo sh