#!/bin/bash

#sudo apt-get remove thunderbird pidgin hexchat
# 对接chrome
rm -fr ~/.config/google-chrome && ln -s ~/WORK/google-chrome ~/.config/google-chrome
# 安装常用软件
sudo apt-get install -y curl git git-review git-svn gitk meld sublime-text gawk kuaipan4uk gufw xmind terminator gnome-disk-utility freemind synaptic transmission-gtk
sudo ufw enable && sudo ufw default deny
# 安装 docker
sudo apt-get install -y apparmor curl php5-cli && curl -s https://get.docker.io/ubuntu/ | sudo sh
# 安装 虚拟机并设置好账户
sudo apt-get install -y virtualbox
sudo sed -i 's/vboxusers:x:124:/vboxusers:x:124:chenlianghong/g' /etc/group
sudo sed -i 's/\/home\/chenlianghong:\/bin\/zsh/\/home\/chenlianghong:\/bin\/bash/g' /etc/passwd #深度系统奇葩
# 安装 安卓模拟器
sudo apt-get install genymotion
# 安装lxde桌面
sudo apt-get install -y xcompmgr lxde
# 重启
sudo reboot

# 基本软件安装
sudo apt-get install -y git git-review git-svn firefox firefox-locale-zh-hans sublime-text
#安装 mysql 数据库 修改端口3306为3309
sudo apt-get install -y install mysql-client mysql-server
sed -i -e"s/^bind-address\s*=\s*127.0.0.1/bind-address = 0.0.0.0/" /etc/mysql/my.cnf
sed -i -e"s/^port\s*=\s*3309/port = 3309/" /etc/mysql/my.cnf
# 内置工具命令
sudo cp ~/WORK/mytar /usr/local/bin/
sudo chmod 555 /usr/local/bin/mytar
# vim
# 获取配置
curl https://j.mp/spf13-vim3 -L > spf13-vim.sh && sh spf13-vim.sh
# curl https://j.mp/spf13-vim3 -L -o - | sh #更新
# casper
git clone git://github.com/n1k0/casperjs.git
cd casperjs
ln -sf `pwd`/bin/casperjs /usr/local/bin/casperjs
#nodejs 和 npm 安装
curl -sL https://deb.nodesource.com/setup | sudo bash -
sudo apt-get install -y nodejs
#风格检查
sudo npm install -g jscs
sudo npm install -g jshint
sudo npm install -g coffeelint
#coffeelint -f ~/coffeelint.json <coffee-file>
sudo npm install -g csslint
#csslint --ignore=adjoining-classes,text-indent,import,ids --format=compact <css-file>

# 安装 docker
sudo apt-get update
sudo apt-get install docker.io
sudo ln -sf /usr/bin/docker.io /usr/local/bin/docker
sudo sed -i '$acomplete -F _docker docker' /etc/bash_completion.d/docker.io
# 或者
# curl -s https://get.docker.io/ubuntu/ | sudo sh





# 常用命令
# docker save image_name > /home/date.image_name.tar
# docker load < /home/save.image.tar
# sudo docker cp 7bb0e258aefe:/etc/debian_version . #拷贝容器中的一个文件到本地
# sudo service docker restart
# sudo docker stop $(docker ps -aq) && sudo docker rm $(docker ps -aq)
# docker exec -it [container-id] bash # other tty
# sudo docker run --rm -i -t -p 80:80 -p 3306:3306 -v ~/WORK/home.chenlianghong:/home/chenlianghong -v ~/WORK/app:/app -v ~/WORK/mysqldb:/var/lib/mysql -v ~/WORK:/home/chenlianghong/WORK -e MYSQL_PASS="admin" leehom/lamp
# php -S 0.0.0.0:8080
# php artisan serve --host=0.0.0.0 --port=8000 &> $(date +%Y%m%d_%H%M%S).php.artisan.serve.log
# php artisan app:install
# php artisan app:update
# php artisan migrate
# php artisan db:seed
# composer dump-autoload
# php artisan migrate --package=cartalyst/sentry
sudo docker run --rm -i -t -p 80:80 -p 3306:3306 -v /media/chenlianghong/DATA/important/WORK/home.chenlianghong:/home/chenlianghong -v /media/chenlianghong/DATA/important/WORK/app:/app -v /media/chenlianghong/DATA/important/WORK/mysqldb:/var/lib/mysql -e MYSQL_PASS="admin" leehom/lamp

sudo docker run --rm -i -t -p 80:80 -p 3306:3306 -v ~/WORK/home.chenlianghong:/home/chenlianghong -v ~/WORK/app:/app -v ~/WORK/app/deepin-officialwebsite.conf:/etc/apache2/sites-enabled/deepin-officialwebsite.conf -v ~/WORK/mysqldb:/var/lib/mysql -v ~/WORK:/home/chenlianghong/WORK -e MYSQL_PASS="admin" leehom/lamp
# prefix=$(date +%Y%m%d_%H%M%S)
# for args in $@
# do
#     echo "$(date +%Y-%m-%d_%H:%M:%S) $args"
#     tar -zcpf $prefix.$args.tar.gz  $args
# done
# mytar folder1 [folder2 [folder3 ...]]
# sudo service docker restart
# docker exec -it [container-id] bash # other tty
# sudo docker run --rm -i -t -p 80:80 -p 3306:3306 -v ~/WORK/home.chenlianghong:/home/chenlianghong -v ~/WORK/app:/app -v ~/WORK/mysqldb:/var/lib/mysql -v ~/WORK:/home/chenlianghong/WORK -e MYSQL_PASS="admin" leehom/lamp





# ----------------------------------------------------
# 安装开发环境
#sudo apt-get install lamp
#sudo rm -fr /var/www/html && sudo ln -s ~/WORK/websites/deepin/public /var/www/html
#curl -sS https://getcomposer.org/installer | php #安装composer
# ----------------------------------------------------

# ----------------------------------------------------
# #!/bin/bash
# sudo cat > /tmp/chenlianghong.cron <<EOF
# # 备份安装的软件包，方便没网络重装软件时需要
# 0,30 * * * * bash ~/WORK/bak.apt-get.cache.sh

# EOF
# crontab -u chenlianghong /tmp/chenlianghong.cron
# sudo cat /var/spool/cron/crontabs/chenlianghong

# # curl -s https://get.docker.io/ubuntu/ | sudo sh
# # 0 12 * * * bash ~/WORK/update.gits.sh
# ----------------------------------------------------


